/*
ELIMINAR SECUENCIA CUANDO SALE ERROR EN 360 DE QUE NO DEJA AVANZAR POR SECUENCIA 

*/

---Eliminar Secuencia---
SELECT SECUENCIA_OFERTA_SINU, ESTADO, ID_EXTERNO, t.* FROM ZOHO_CUN.CUNT_ZOHO_REGISTRO_VIRTUAL t
WHERE NUMERO_DOCUMENTO='1122339072' 
ORDER BY FECHA_REGISTRO DESC;
